apiVersion: v1
kind: ConfigMap
metadata:
  name: configs
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
    {{- include "microservices.configmap.labels" . | nindent 4 }}
data:
  songs-db-port: {{ .Values.config.songsDbPort | quote }}
  resources-db-port: {{ .Values.config.resourcesDbPort | quote }}
  songs-ms-port: {{ .Values.config.songsMsPort | quote }}
  resources-ms-port: {{ .Values.config.resourcesMsPort | quote }}
