apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.songsPvc.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.songsPvc.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.songsPvc.storage }}
  volumeName: {{ .Values.songsPv.name }}
