apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
type: Opaque
stringData:
  SONGS_DB_USER: {{ .Values.postgres.songsDbUser | quote }}
  SONGS_DB_PASSWORD: {{ .Values.postgres.songsDbPassword | quote }}
  RESOURCES_DB_USER: {{ .Values.postgres.resourcesDbUser | quote }}
  RESOURCES_DB_PASSWORD: {{ .Values.postgres.resourcesDbPassword | quote }}
