apiVersion: v1
kind: Service
metadata:
  name: songs-db-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
spec:
  selector:
    app: songs-db-pod
  clusterIP: None
  ports:
    - port: {{ .Values.songsDb.port }}
      name: songs-db
