apiVersion: v1
kind: Service
metadata:
  name: resource-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: resources-app-pod
  ports:
    - protocol: TCP
      port: {{ .Values.resourcesService.nodePort }}
      targetPort: {{ .Values.resourcesService.port }}
