apiVersion: v1
kind: Namespace
metadata: 
  name: k8s-program

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: configs
  namespace: k8s-program
data:
  songs-db-port: "5432"
  resources-db-port: "5433"
  songs-ms-port: "8080"
  resources-ms-port: "8080"

---

apiVersion: v1
kind: Service
metadata:
  name: resource-service
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: resources-app-pod
  ports:
    - protocol: "TCP"
      port: 8083
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-deployment
  namespace: k8s-program
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resources-app-pod
  template:
    metadata:
      labels:
        app: resources-app-pod
    spec:
      containers:
        - name: resources-container
          image: localhost/k8s/resources-image:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 5
          env:
            - name: RESOURCES_MS_PORT
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: resources-ms-port
            - name: RESOURCES_DB_URL
              value: resources-db-service
            - name: RESOURCES_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: resources-db-port

---

apiVersion: v1
kind: Service
metadata:
  name: song-service
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: songs-app-pod
  ports:
    - protocol: "TCP"
      port: 8084
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: songs-deployment
  namespace: k8s-program
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: songs-app-pod
  template:
    metadata:
      labels:
        app: songs-app-pod
    spec:
      volumes:
        - name: songs-pv-storage
          persistentVolumeClaim:
            claimName: songs-pvc
      containers:
        - name: songs-container
          image: localhost/k8s/songs-image:2.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"
              name: songs-pv-storage
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 5
          env:
            - name: SONGS_MS_PORT
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: songs-ms-port
            - name: SONGS_DB_URL
              value: songs-db-service
            - name: SONGS_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: configs
                  key: songs-db-port